server:
  port: 8083

spring:
  application:
    name: score-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/scoredb}
    username: ${SPRING_DATASOURCE_USERNAME:scoreapp}
    password: ${SPRING_DATASOURCE_PASSWORD:scorepass123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# URLs de otros microservicios
services:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  game:
    url: ${GAME_SERVICE_URL:http://localhost:8082}

logging:
  level:
    com.mindgames.scoreservice: DEBUG
    org.hibernate.SQL: DEBUG

